### ISSUE TITLE
window.twttr.ready is not a function

### ISSUE THREAD

**Issue by devspinn** [capaj/react-tweet-embed#12]
on line 55 of tweet-embed.js `window.twttr.ready().then(function (_ref) {`

**Comment by bebraw** [comment]
At least in my case it was my ad blocker that broke it. Make sure it's not the same for you.

**Comment by capaj** [comment]
@devspinn let me know if it's an adblocker. If I don't hear from you, I will close in 72 hours.

**Comment by bf** [comment]
"72 hours" :laughing:

**Comment by capaj** [comment]
Touché @bf
