### ISSUE TITLE
"ReferenceError: Can't find variable: callbacks" on Safari iOS when bundled w/ webpack 

### ISSUE THREAD

**Issue by bf** [capaj/react-tweet-embed#15]
When bundling react-tweet-embed with webpack, I receive an error when visiting the page with Safari on iOS: `ReferenceError: Can't find variable: callbacks`.

**Comment by bf** [comment]
Oh, the problem is that Safari on iOS cannot process the ES6, and babel is not transpiling to ES5 because we have whitelisted the node_modules folder.

**Comment by capaj** [comment]
@bf you can try aliasing it to the es5 version of the bundled file. Better solution would be to transpile your node_modules as well if you're targeting these older browsers.
