### ISSUE TITLE
Error with class properties in IE 11

### ISSUE THREAD

**Issue by vincentfretin** [capaj/react-tweet-embed#16]
Hi,
I had a hard time figuring out why webpack >= 2 produced a build of my project which contained `()=>`' in it. IE 11 gives a Syntax error on it.
It was because this project is using the class properties to autobind functions and webpack includes the source code pointed by the module key in package.json.
I tried to force my webpack config to transpile this package, but it fails because babel-loader takes the .babelrc from this project to transpile it.
If I remove node_modules/react-tweet-embed/.babelrc, babel-loader takes my .babelrc config and this transpiles fine.
Or if I write a `node_modules/react-tweet-embed/.babelrc` file with the following content:
```
{
  "plugins" : ["transform-class-properties"],
  "presets": ["es2015", "react"]
}
```

it works too. Would you consider changing the .babelrc to this?
In general libraries that expose a module key in package.json point to ES module but transpiled to ES5 as far as I can tell.

**Comment by vincentfretin** [comment]
This is interesting http://2ality.com/2017/06/pkg-esnext.html
It says this for the module key: `module is restricted to what is currently supported by Node.js.`
and if you want the raw code, you need another key like `jsnext:main`.

Oh, I just tested something. In my project, if I put the babel config in babel-loader like this

```
            use: {
              loader: 'babel-loader',                                              
              options: {
                "plugins" : ["transform-object-rest-spread", "transform-class-properties"],
                "presets" : ["es2015", "react"]
              },
              include: [
                path.join(__dirname, 'js'),
                path.join(__dirname, 'node_modules/react-tweet-embed')
              ]
          }
        },
```
instead of using a .babelrc file, it will completely ignore the .babelrc file in your package, and it will transpile ok.

So I guess I have a workaround for my issue. But please consider transpiling to ES5 for the module key. Thanks.

**Comment by capaj** [comment]
@vincentfretin where I used this, I transpiled all the code with babel, even inside the node_modules.
I will let it transpile to ES5 in 1.0.8 for the built file

**Comment by vincentfretin** [comment]
Thanks. Perfect.
