### ISSUE TITLE
Invariant Violation: Expected a component class, got [object Object]

### ISSUE THREAD

**Issue by Dumanix** [capaj/react-tweet-embed#17]
Hi

Looks easy to use but it doesn't work...

ERROR: Invariant Violation: Expected a component class, got [object Object].
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property '_currentElement' of null

**Comment by capaj** [comment]
which version of react are you using?

**Comment by Dumanix** [comment]
I'm using react native. I think this component is for react? if so, do you have a react native version?

**Comment by capaj** [comment]
Nope. Sorry. You'll have to use:
https://dev.twitter.com/twitterkit/android/show-tweets
