### ISSUE TITLE
not loading inside Cordova

### ISSUE THREAD

**Issue by edwarddistel** [capaj/react-tweet-embed#18]
Great package. Ever tried it inside Apache Cordova?

It works fine for me on a website but the <iframe> comes back empty when loaded in a Cordova app.

if I modify `tweet-embed.js` and `tweet-embed.es.js` to force https, the code loads but the data still doesn't.

Not getting any errors in the console, and the Network inspector says the HTTPS requests respond with 200.

Any idea on how to diagnose further?

**Comment by capaj** [comment]
I don't really have time to test it out in a cordova app myself. I might get to it in next few months, but no promises.

**Comment by edwarddistel** [comment]
Totally forgot about this! This was 4 years ago, I haven't touched Cordova in years. Don't waste your time.

Thanks.
