### ISSUE TITLE
Source code for the latest version?

### ISSUE THREAD

**Issue by dandv** [capaj/react-tweet-embed#24]
`package.json` shows [v1.1.0](https://github.com/capaj/react-tweet-embed/blob/master/package.json#L3), [npm shows v1.1.1](https://www.npmjs.com/package/react-tweet-embed).

**Comment by hsribei** [comment]
This is not good. Thanks for reporting!

**Comment by capaj** [comment]
oh I forgot to push, thanks for the reminder @dandv. Pushed now.
