### ISSUE TITLE
Feature request: text placeholder prop

### ISSUE THREAD

**Issue by dandv** [capaj/react-tweet-embed#26]
Sometimes the app might have already the id and the text of a bunch of tweets, and it would be nice to display a text placeholder before the embedded HTML finishes loading. The syntax could look like this:

    <TweetEmbed id='692527862369357824' text='¯\_(ツ)_/¯'/>

**Comment by capaj** [comment]
I'd rather name it `placeholder` and it will take a string or a react node.

**Comment by capaj** [comment]
fixed in 84546b396f47cc901b142b362eb49530ddb6c894
released as 1.2.1

**Comment by dandv** [comment]
Thanks for implementing that! I can't figure out why it's not working, though:

https://codesandbox.io/embed/billowing-smoke-92zyu

I don't see the placeholder text at all.

**Comment by dandv** [comment]
Actually I do see the text, but very, very briefly, and it takes 3 seconds of white space after the text clears and until the tweets load. [Demo](https://cryptoclimate.io/).

Wondering if the text could be preserved until the tweets actually show, but that seems to be driven by when the onload callback is called, which is out of the library's control?

Another idea would be to have the children as a placeholder, instead of a prop. That way, the placement and size of the text can be controlled by the developer.
