### ISSUE TITLE
Could not resolve dependency: npm peer react@"^15.0.0 || ^16.0.0" from react-twitter-embed@3.0.3

### ISSUE THREAD

**Issue by filiplucian** [capaj/react-tweet-embed#55]
Describe the bug
I can not install react-twitter-embed on the Next.js version 12.0.7.

To Reproduce

Go to the next.js project directory.
Open the terminal in the project directory
Run npm install --save react-twitter-embed
See error.
Expected behavior
A clear and concise description of what you expected to happen
![2021-12-28_01h13_07](https://user-images.githubusercontent.com/42959407/147512913-7db5acda-6b62-4ccf-9bf9-0be659500567.png)
.

**Comment by capaj** [comment]
this is a different npm package. I suggest you report this in https://github.com/saurabhnemade/react-twitter-embed
