### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by suppprith** [capaj/react-tweet-embed#56]
![image](https://user-images.githubusercontent.com/78292833/154054811-088b2f42-1c4f-4deb-80a5-0f6c85844d60.png)
Got this error in a vite react project

**Comment by huedaya** [comment]
how did you fix the issue? @staticbug6

**Comment by gaschneidr** [comment]
For anyone reading this issue, I found a fix for it. See the following link for an explanation [link](https://adambien.blog/roller/abien/entry/uncaught_referenceerror_process_is_not).

Essencially, you add the following snippet to a js file before you import the `react-tweet-embed`

```
window.process = {
    env: {
        NODE_ENV: 'development'
    }
}
```

Don't know if there's a better fix for it, but it made it work here.
